import math
import random

import numpy as np


def calc_mid_point(p1, p2):
    """
    Function that calculates the mid-point between two points
    :param p1:          point 1
    :param p2:          point 2
    :return:
    """
    return [(p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2]


def random_points_with_spacing(width, height, min_dist, count):
    """
    Function to randomly draw random points within a certain distance
    :param width:       width of the map
    :param height:      height of the map
    :param min_dist:    minimum distance between the point
    :param count:       number of random points to draw
    :return:
    """
    points = []

    while len(points) < count:
        p = [random.uniform(0, width), random.uniform(0, height)]
        if all((p[0]-q[0])**2 + (p[1]-q[1])**2 >= min_dist**2 for q in points):
            points.append(p)

    return points


def calc_quadrant(c, p):
    """
    Function that calculates the quadrant of a point p relative to the center c
    :param c:           Center point
    :param p:           Target point evaluated relative to the center
    :return:
    """
    # Calculate difference between target point coordinates and the center's
    x_diff, y_diff = p[0] - c[0], p[1] - c[1]

    # Assign quadrant
    if x_diff >= 0 and y_diff > 0:
        return "Q1"
    elif x_diff < 0 and y_diff >= 0:
        return "Q2"
    elif x_diff <= 0 and y_diff < 0:
        return "Q3"
    elif x_diff > 0 and y_diff <= 0:
        return "Q4"
    else:
        raise ValueError(f"Quadrant not defined for c = {c} and p = {p}\n ")


def calc_phi_points(p1, p2):
    """
    Calculate angle between the line generated by the points
    p1, p2 and the X-axis of the map
    :param p1:      point 1 (x, y)
    :param p2:      point 2 (x, y)
    :return:
    """
    return np.arctan2(p2[1] - p1[1], p2[0] - p1[0])


def calc_dist_points(p1, p2):
    """
    Calculate the distance between two points
    :param p1:      point 1 (x, y)
    :param p2:      point 2 (x, y)
    :return:
    """
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)
